services:
  windows11:
    image: dockurr/windows:latest
    container_name: windows11

    environment:
      VERSION: "11"

      CPU_CORES: "2"
      RAM_SIZE: "4G"
      DISK_SIZE: "64G"

      USERNAME: "Ben"
      PASSWORD: "1123581321"

      MTU: "1486"
      DISPLAY: "web"

    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net

    cap_add:
      - ALL

    security_opt:
      - seccomp=unconfined

    privileged: true

    ports:
      - "8006:8006/tcp"
      - "3389:3389/tcp"

    volumes:
      - ./windows/data:/storage
      - ./Win11.iso:/custom.iso:ro

    restart: on-failure
    stop_grace_period: 2m